params            = action *(*space action)
action            = content-path / output-path / exclude / static-path
word              = (ALPHA / DIGIT / "/") *(ALPHA / DIGIT / "-" / "_" / "." / ":" / "/")
term              = (dquote word *(*space word) dquote / word)
content-path-cmd  = ("--content-path" / "-p")
content-path      = content-path-cmd *space term
output-path-cmd   = ("--output-path" / "-o")
output-path       = output-path-cmd *space term
exclude-cmd       = ("--exclude" / "-e")
exclude           = exclude-cmd *space term 
static-path-cmd   = ("--static-path" / "-s")
static-path       = static-path-cmd *space term 
space             = " "
dquote            = DQUOTE
